version: "3.3"
services:
  # ainize-EasyOCR:
  #   image: wookbyung/easyocrgpu
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - shared
  locust:
    build:
      context: .
    environment:
      # TARGET_URL: 
      TARGET_URL: https://easyocrgpu-wook-2.endpoint.ainize.ai/
    ports:
      - "8089:8089"
    networks:
      - shared
networks:
  shared: